# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install atomac
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Python version
      run: |
        python --version
        ls /
        wget https://github.com/sparkwj/misc/releases/download/gtja/gtja.app.zip
        unzip gtja.app.zip
        ls
        mv gtja.app /Applications
